# Typical setup for benchmarking:
# - create a new GitHub branch
# - trigger benchmark.yml on the new branch
# - open PR to main
# - review the PR
# - squash and merge

name: benchmark

on:
  workflow_dispatch:

env:
  GH_API_TOKEN: ${{ secrets.GH_API_TOKEN }}

jobs:

  benchmark-bsd:
    name: ${{ matrix.os }}
    runs-on: ubuntu-latest
    permissions:
      contents: write

    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        include:
          - os: netbsd
            version: "10.1"
            rust_install: |
              sudo pkgin update
              sudo sysctl kern.maxfiles=20000
              ulimit -n 3404
              curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
              export PATH=$HOME/.cargo/bin:$PATH
          - os: openbsd
            version: "7.8"
            rust_install: |
              sudo sysctl -w kern.maxfiles=20000
              ulimit -n 1024
              sudo pkg_add rust rust-rustfmt rust-clippy
          - os: freebsd
            version: "14.3"
            rust_install: |
              sudo pkg update
              curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
              export PATH=$HOME/.cargo/bin:$PATH

    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.ref_name }}

      - name: bench
        uses: cross-platform-actions/action@v0.32.0
        with:
          operating_system: ${{ matrix.os }}
          version: ${{ matrix.version }}
          run: |
            set -e
            ${{ matrix.rust_install }}
            
            echo "Running benchmarks..."
            cargo build --release --bin spawn_process
            cargo bench

      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "update benchmarks for ${{ matrix.os }}"

  benchmark:
    name: ${{ matrix.os }}-latest
    runs-on: ${{ matrix.os }}-latest
    needs: benchmark-bsd
    permissions:
      contents: write
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        include:
          - os: ubuntu
          - os: macos
          - os: windows

    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.ref_name }}
      - uses: dtolnay/rust-toolchain@stable

      - name: bench
        run: |
          cargo build --release --bin spawn_process
          cargo bench

      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "update benchmarks for ${{ matrix.os }}"
