name: benchmark

on:
  workflow_dispatch:

env:
  GH_API_TOKEN: ${{ secrets.GH_API_TOKEN }}

jobs:

  benchmark-freebsd:
    name: freebsd
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.ref_name }}

      - name: bench
        uses: cross-platform-actions/action@v0.32.0
        with:
          operating_system: freebsd
          version: 14.3
          run: |
            sudo pkg update
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
            
            export PATH=$HOME/.cargo/bin:$PATH
            
            echo "Running benchmarks..."
            cargo bench

      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "update benchmarks for freebsd"

  benchmark:
    name: ${{ matrix.os }}-latest
    runs-on: ${{ matrix.os }}-latest
    needs: benchmark-freebsd
    permissions:
      contents: write
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        include:
          - os: ubuntu
          - os: macos
          - os: windows

    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.ref_name }}
      - uses: dtolnay/rust-toolchain@stable

      - name: bench
        run: cargo bench

      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "update benchmarks for ${{ matrix.os }}"
